### PR TITLE
[utils] switch to EXTREMUM from alexandria at commit b1c6ee03

### PR DESCRIPTION
**Pull request by gaya-**
Pretty trivial.

Don't anticipate any side effects.

### CODE REVIEW

**Comment by phyrog** [comment]
Shouldn't this also revert the shadowing imports from #35? Also, shouldn't https://github.com/cram-code/cram_3rdparty/issues/8 be merged first to have the extremum function from alexandria available?

**Comment by gaya-** [comment]
I don't understand one the shadowing stuff was needed on the first place. I'll leave it to you guys to revert it back.

**Comment by airballking** [comment]
@phyrog is right, we should now remove ```extremum``` from the list of shadowing imports in other packages.

**Comment by phyrog** [comment]
@airballking It also needs to be removed from cram_highlevel (see https://github.com/cram-code/cram_highlevel/pull/47), although I'm not sure if `extremum` is called directly in cram_highlevel

**Comment by airballking** [comment]
@phyrog done,

**Pull request merged**
